### ISSUE TITLE
Place for implementation

### ISSUE THREAD

**Issue by bmoneke** [pymeasure/leco-protocol#25]
This project concerns itself with the **protocol**. Where do we want to have concrete implementations in programming languages?

My idea:

- This repository contains as well the protocol definition (text files)
- This repository contains also the code of the python reference implementation (published as pypi package)
- More specialized python programs (Actors for different libraries, specialized GUI etc.) may enter another repository or even just a download place (so no review process for us)
- Programs in different languages are placed in the same place as "additional python code".

**Comment by bilderbuchi** [comment]
The way I thought to handle this:
Keeping the specification and the (reference) implementation separated, like for example ASDF does: https://github.com/asdf-format/asdf-standard (the spec), https://github.com/asdf-format/asdf (the Python package). Why should other people implementing portions of it after the spec need to concern themselves with noise/issues from the Python implementation. Also, the release cycle of implementation and spec might (will) be different, and that will be messy to keep in order.

I realise that this will mean a little more effort for us while spec _and_ code evolve side-by-side, but we could probably offset by doing as much of the design as feasible _first_, and then start the implementation, and feed back the lessons learned into the spec.

I think some Actors for libraries (those we can support) should be in the reference implementation directly. The rest should tie into our package via Python "entry points" (https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/#using-package-metadata), which allows them to register into our namespace. So, users just have to install a plugin package in addition to the implementation package to get the Actor variant they need.

In principle, we could do the same for other programs that want to use parts of the implementation, but publishing those standalone would also be ok. I guess it will be decided on a case-by-case basis.

We do not (and should not) have control over where others host their packages. The pymeasure org should host the specification, the Python implementation, and any other things we want to maintain ourselves.

**Comment by bklebel** [comment]
I would also think that we rather put the implementation in a separate repository, which in turn will be much cleaner. As long as it is under the pymeasure org, it should be reasonably close-by. Having Actors for supported libraries right inside the reference implementation would also be good, especially if we support more than pymeasure, as it gives a larger set of examples of how to go about developing a new Actor for a certain library. However, these would be high-level Actors, in a sense of "if you have a `pymeasure.Instrument`, you can access it through this Actor", but a user might want to create a specific Actor for specific Devices, for their own purposes, these would then not necessarily need a place in the reference. Possibly we can have a list of links to specific Actors/Processors where people can showcase their things, possibly we can have a separate folder for contributed specifics (like a special PID version or similar, or specific Actors, as mentioned).

**Comment by bmoneke** [comment]
I see and accept your points regarding separation of definition and code.
Thanks for your ideas.

**Comment by bmoneke** [comment]
How do we call the python repo? Py_ecp?

On pypi is already a package "ECP" and another one "py-ECP"...

"Control-protocol" is still free.

**Comment by bklebel** [comment]
huh, it turns out that "ECP" is an abbreviation for quite a few things, who would have thought...
However, the P in ECP for us is the "protocol", which I think we do not need in our implementation. We could keep matters simple and go for ECI for "Experiment-Control-Implementation", i.e. for example py-eci or pyeci, using only two characters (like "ec") has many overlaps to other packages. Another thing would be pymeasurecontrol, but I guess that would tie us too closely to `pymeasure` instead of the ECP here.

**Comment by LongnoseRob** [comment]
How about "ECDM" - Experiment Control & Data Management or "ECDH" Expermiment Control & Data Handling ?

**Comment by bilderbuchi** [comment]
Name collisions are fun! I guess at this point in history, all 3 letter acronyms are probably spoken for, already :D

At this point, we could still rename the _whole_ thing if we find a better fitting and descriptive name, but "Experiment Control Protocol" was the best we could come up with. Ideas for better names?

> "Control-protocol" is still free.

I think that's too generic a name -- what do you control? remote cars? server network stacks?

>  P in ECP for us is the "protocol", which I think we do not need in our implementation. 

I'm afraid I don't follow that logic. I think the "P" needs to be preserved. E.g. The Python module implementing HTTP is also called `http`, not `htt(i)`.

`ecpi` would be an option, but then I've never seen a package appending an `i` for "implementation".

> Another thing would be pymeasurecontrol, but I guess that would tie us too closely to pymeasure instead of the ECP here.

Agreed.

> How about "ECDM" - Experiment Control & Data Management or "ECDH" Expermiment Control & Data Handling ?

ECDH is, of course, [already taken](https://pypi.org/project/ecdh/). :D 

"Experiment Control and Data Management Protocol" is quite the mouthful, but at least `ecdm` is still free. I think the "data management" kinda dilutes the name/focus, though. 

"Experiment Control Protocol" is a protocol about controlling experiments. One could ask "what kinds of experiments"? (on lab rats?) -- "experiment" was the most concise way to describe what we do .. "lab setups", "connected devices",...felt worse. 
We could tack on a "Scientific" at the beginning, but this is not only about scientific setups (but also R&D etc), and "SECP" does not roll off my tongue, at least. :stuck_out_tongue_closed_eyes:

**Comment by bmoneke** [comment]
It fits quite a few packages: pyplot, pytrinamic (trinamic motion control), pyvisa, pyserial, pyqt...

I like, that it is short, such that people do not have to invent (different) abbreviations at import time.

👍 For pyecp

**Comment by bklebel** [comment]
I am not sure in what way pyecp rolls off my tongue better than pysecp, a consonant between vowels does sometime help, and the problem is more with the "cp" at the end, I think. "pysep" is of course also already taken, "pysemp" is not - for py-Scientific-Experiment-Management-Protocol. After all, we are not only controlling but managing in a broader sense, even though we are not just managing data (I agree that "data management" is not a good option, reminds me way too much of "data management plan", and now THAT is an unpopular word in town right now). 

What do you think about `pysemp`? 

SEMP in itself could also be an okayish acronym for the whole thing, I think, reminds me of "semper", latin for always, and one goal (I think, at least for me), is to make the control which we have e.g. with pymeasure, a continuous thing, perpetually running. 
Additionally, in my head, I vocalize ECP as individual characters, E-C-P - this is fine by itself, because it works fine, but a spoken word beats that, I think.

**Comment by bilderbuchi** [comment]
For me, that would spell "py-ee-cee-pee" vs. "py-sekp". 
But yeah, if we find a thing that can be "said" or nearly-said ("SCPI" and "skippy"), that would be good, too. Although, then we are approaching acronym-retconning-for-a-nice-proposal-title terrritory, which I'm not a big fan of. Bonus (well, malus) points for picking letters from the middle of words.

We could also go totally sideways and just use an unconnected name like so many services do. Maybe "Karli"? 
*just kidding, to be clear*

I don't prefer an S for Scientific in the name, I don't see this restricted in scope to Science.

**Comment by bklebel** [comment]
> I'm afraid I don't follow that logic. I think the "P" needs to be preserved. E.g. The Python module implementing HTTP is also called http, not htt(i).

Ok, you have a point :D

Now, I did not go to pick single letters from the middle of words, but maybe multiple ones, arrived at `exopy`, and found [exopy](https://pypi.org/project/exopy/) - `excop` would still be available, but I am not sure whether that is perceived as totally unrelated thing. `ecopy` is also aready taken. 

> I don't prefer an S for Scientific in the name, I don't see this restricted in scope to Science.

Ok, agreed, this could be used for much else, in principle. However, I don't think R&D in the private sector is actually "unscientific", or at least I hope so :D - but still, R&D was now only one example out of many possible ones, so "s" for scientific goes out of the window I guess. 

Changing tack, what about `pycemp`? not scientific, but "controlled experiment management protocol" - it should definitely be better than "uncontrolled/uncontrollable" protocols ;)
What do you think? 

In general I am quite in favor of something that can be "said", but if everything sensible is already taken...

**Comment by bilderbuchi** [comment]
We could also throw "laboratory" into the mix/instead of "experiment"  somehow? 
LECOP - Laboratory Experiment COntrol Protocol, although saying it out loud this seems Canadian French for "the policeman" :rofl:

**Comment by bklebel** [comment]
`leco` sounds great, I think! also because it is close to LEGO, and we would like to try and use such a modular approach. Also, `pyleco` is still available, and if we import from `pymeasure`, we could keep that style, as was suggested above - for example, pyvisa also changed to the import name `pyvisa` recently, from just `visa`, didn't they? 

I think I would like to avoid lecop in the implementation package, but as name, why not :D

**Comment by bmoneke** [comment]
Thanks for the great ideas. I like these images and mottos.

I propose:
- Leco for the system / implementation /setup... (would be the name of this repository) 
- pyleco is the python code of leco (name of repository, pypi name, and package import name) 
- lecop is the protocol definition, the "rules" themselves of leco

**Comment by bilderbuchi** [comment]
Sounds good. One suggestion: We could do as you propose (call the "system" LECO, the python implementation pyleco), but name this repo "leco-protocol". This would prominently preserve the "protocol" nature/purpose of this repo. This is similar to how ASDF does it.
Agreed?

**Comment by LongnoseRob** [comment]
> `leco` sounds great, I think! also because it is close to LEGO, and we would like to try and use such a modular approach. Also, `pyleco` is still available, and if we import from `pymeasure`, we could keep that style, as was suggested above - for example, pyvisa also changed to the import name `pyvisa` recently, from just `visa`, didn't they?

`leco` sounds great indeed!
BTW: on the change form `visa` to `pyvisa`: "_recently_" was 2019 --> this [PR](https://github.com/pyvisa/pyvisa/pull/448)

**Comment by bilderbuchi** [comment]
The king is dead, long live the king!
https://github.com/pymeasure/leco-protocol

pyleco: 
https://github.com/pymeasure/pyleco
https://pypi.org/project/pyleco/0.0.1.dev0/

**Comment by bmoneke** [comment]
Thanks for doing the renaming and reserving the pypi name.
