### ISSUE TITLE
Component IDs

### ISSUE THREAD

**Issue by bmoneke** [pymeasure/leco-protocol#27]
Each Component has some ID to address it in the ECP network.

In #22 we decided on **namespaces**, such that a **full** Component ID is "namespace.individualID" with its **indidividual** ID.
For the control protocol, it is acceptable, that a Component is not aware of its namespace (as discussed in #22) nor does it matter, that one ID is equal to the beginning of another one (for example "ID1" and "ID105" are different).

Now for the data protocol:

- For consistency, we should use the same ID as in the control protocol
- if the individual IDs are not globally unique (for that reason we have namespace), the sender name should be the full ID, such that the Component has to be aware of its full ID
- Zmq topic filtering compares from the beginning and stops, if the searched string is matched, regardless of the following chars. So if you subscribe to "names.ID1", you get also messages from "names.ID105" etc. Therefore, names have to be unique in regard to substrings as well.

A consequence from the second point: If Components are aware of their namespace (during initial contact, probably), they can use that full ID in the communication instead of their individual ID. That way, the Coordinators do not have to modify the names during transit anymore.

EDIT: Without the modification of the name, we can do "zero-copy", sending a message again without copying, assigning a new buffer etc.

Therefore, I prefer the idea, that the message stays the same from beginning to end. Only maybe the sender's name may be prepended by the namespace, if the sender forgot.

**Comment by bmoneke** [comment]
I found a solution for the wrong subscription if there are similar names: while publishing, the full name is appended by a dot (which is already a reserved character due to the namespace).
That way you can subscribe to "ID1" if you want to receive messages from all Components starting with that string, and you can subscribe to "ID1.", if you want only that single component, but not "ID105".
(for brevity, I ignored the namespace)

A side note regarding filtering: the whole string has to match, therefore if you subscribe to "ID105", you will not get meddages from "ID1".

**Comment by bilderbuchi** [comment]
> * Zmq topic filtering compares from the beginning and stops, if the searched string is matched, regardless of the following chars. So if you subscribe to "names.ID1", you get also messages from "names.ID105" etc. Therefore, names have to be unique in regard to substrings as well.

On the surface, that feels crazy/really inconvenient. I guess we can work around that by restricting the format of our names?
Do you know where that is documented?

**Comment by bmoneke** [comment]
https://zeromq.org/socket-api/#publish-subscribe-pattern

I already proposed a solution (alternatively, we could require a fixed length ID).

**Comment by bmoneke** [comment]
Another question regarding full names for routing: shall we allow to drop the name space, while addressing a Component in the same name space. That could be useful for manual handling (shortens the names). So instead of "namespace.ID" the recipient address will be ".ID".

I think, that a starting dot is quite common as a relative / local indicator.

We can allow this shorthand later on without compromising the core functionality.

**Comment by bilderbuchi** [comment]
It will be useful for small/single-node setups to not have to prepend a useless `Coordinator1.` all the time, but we might file that for later iterations (maybe we should have a backlog milestone already).

**Comment by bmoneke** [comment]
I edited that my preference are unchanged messages from beginning to end.

**Comment by bmoneke** [comment]
If we use the ID also as zmq routing frame (which is advisable), the ID of a namespace ("Coordinator name") and of Components has the following restrictions:
"A routing id must be at least one byte and at most 255 bytes long. Identities starting with a zero byte are reserved for use by the ØMQ infrastructure." ([API set_sockopt ZMQ_ROUTING_ID](http://api.zeromq.org/master:zmq-setsockopt#toc50))

At least in python, I was able to connect with a second socket under the same identity to a ROUTER socket contrary to the statement, that the connection will be refused. However, no message of the second peer reached the ROUTER socket, nor was any error raised.

- [ ] Verify, that an usurping DEALER socket is refused.

`r.ROUTER_MANDATORY = True` makes the router raise an error, if the ID does not exist: "ZMQError: Host unreachable" (python), see [API doc on ROUTER_MANDATORY](http://api.zeromq.org/master:zmq-setsockopt#toc48)

**Comment by bklebel** [comment]
Very good that you tested that! 

I hope that the zmq restrictions on ID's will not be too restrictive for our settings? 255 ASCII characters should be enough even for human-readable names for the number of Components we aim at. If somebody wants to connect loads of Components, they will just have to come up with less-than-easily-human-readable naming schemes. 
It just needs to be put into the protocol, and possibly checked for in the implementation

Let's hope that the zmq issue you opened will be resolved quickly.

**Comment by bmoneke** [comment]
> Let's hope that the zmq issue you opened will be resolved quickly.

Someone asked for help regarding that usage (not exactly to finish it) in 2016 and the answer was:
"Setting the identity is obsolete, instead identification of peer should be part of the handshake at the application level. New server socket type doesn't have identity anymore, routing id which is integer." (https://github.com/zeromq/libzmq/issues/2010#issuecomment-221788561)

(using a handshake was my initial proposal, as I did not remember this possibility)

Someone else said in that thread, that it is useful exactly for our use case:
"In this case if you have two backed router interfaces and one-to-one connection among client and services (I think this is typical in case of remote object calls) then you have to search connection about client and services twice: once in router socket (for low level socket selection by routing id) and once in the user created router code (replace routing id the the application level address).
Currently if you set the same identity in client to router and router to service channels then you don't have to modify the packet and search anything (except router socket, of course).
I just want mention that identity is very helpful in some situations."

So I do not have a lot of hope that it will be fixed.
A work around using our "connect" handshake:
~~~mermaid
graph TD
    A([Component]) --> B[set IDENTITY]
    B --> C[connect to Co1]
    C --> D[send 'connect']
    D --> E{answer in some time}
    E -- no --> N[set IDENTITY to Null = random]
    E -- yes --> H([be happy])
    N --> C2[connect to Co1]
    C2 --> E2{answer in some time}
    E2 -- no --> X([server offline])
    E2 -- yes --> H
~~~

> I hope that the zmq restrictions on ID's will not be too restrictive for our settings? 255 ASCII characters should be enough

I think it is enough.

> It just needs to be put into the protocol, and possibly checked for in the implementation

- Exactly for that reason did I copy the information into this thread, that it may propagate into our documentation.
- ZMQ says "Invalid argument" (python), if the length is too long, so no check needed on our side.

**Comment by bklebel** [comment]
> Someone asked for help regarding that usage (not exactly to finish it) in 2016 and the answer was:
"Setting the identity is obsolete, instead identification of peer should be part of the handshake at the application level. New server socket type doesn't have identity anymore, routing id which is integer." (https://github.com/zeromq/libzmq/issues/2010#issuecomment-221788561)

Well, it is quite funny how they treat it, since the next sentence in the same comment is 
> I don't think we can remove it as alot of users are using it

I thought that it was a very neat way of doing things, and having zmq do that for us, but if they do not want to, and don't go about fixing issues connected to it, we might want to actually do that on the application level ourselves, with more detailed handshaking in the connecting interaction. Essentially, in this case the control-Coordinator needs to keep an address list where they combine the user-decided ID with the DEALER socket's ID of a given Component. I don't quite like it, as I would have like to avoid that work, but if issues/bugs are not going to be fixed, despite people using this feature, we would be better of having control over it ourselves, I guess. 
Then it would also be better to directly not set identities for the DEALER sockets of Components (fallback option in @bmoneke's diagram above), so that the ROUTER can sort that out internally from the start. 

So, here are two diagrams to illustrate that further. 
In the following, `send multipart` and `recv multipart` are actions taken by the ROUTER. DEALER sockets for CA and CB do not prepend an address by themselves, "0" and "1" is what the ROUTER sees/generates
### successful connects and communication
~~~mermaid
sequenceDiagram
    Note left of CA: DEALER socket 
  
    Note over Co1: Start of connection of CA with Co1  
    CA ->> Co1: recv multipart<br/> | 0 | NameCA | CONNECT | more handshake content
    Note over Co1: code stores {"NameCA": "0"}
    Co1 ->> CA: send multipart <br/> | 0 | ACK | 

    Note over Co1: Start of connection of CB with Co1
    Note right of CB: DEALER socket
    CB ->> Co1: recv multipart <br/> | 1 | NameCB | CONNECT | more handshake content
    Note over Co1: code stores {"NameCB": "1"}
    Co1 ->> CB: send multipart <br/> | 1 | ACK |

    Note over Co1: Start of request-reply messaging
    CB ->> Co1: recv multipart: <br/> | 1 | NameCA | request header | request content |  
    Note over Co1: translating NameCA to zmq identity "0", and "1" to NameCB
    Co1 ->> CA: send multipart <br/> | 0 | NameCB | request header | request content |  
    Note left of CA: generating response for NameCB
    CA ->> Co1: recv multipart <br/> | 0 | NameCB | reply header | reply content |
    Note over Co1: translating NameCB to zmq identity "1" and "0" to NameCA
    Co1 ->> CB: send multipart <br/> | 1 | NameCA | reply header | reply content |

~~~

### unsuccessful second connect with same name
~~~mermaid
sequenceDiagram
    Note left of CA: DEALER socket 
  
    Note over Co1: Start of connection of CA with Co1  
    CA ->> Co1: recv multipart<br/> | 0 | NameCA | CONNECT | more handshake content
    Note over Co1: code stores {"NameCA": "0"}
    Co1 ->> CA: send multipart <br/> | 0 | ACK | 

    Note over Co1: Start of connection of CD with Co1
    Note right of CD: DEALER socket
    CD ->> Co1: recv multipart <br/> | 1 | NameCA | CONNECT | more handshake content
    Note over Co1: ERROR, NameCA is already in use! 
    Co1 ->> CD: send multipart <br/> | 1 | NON-ACK | NameCA already in use, choose another! | more info about CA |
~~~

**Comment by bmoneke** [comment]
We want to keep an address list anyway, therefore it does not increase the work to register the names.

As we do not need to use the frames for routing, we could use individual frames for namespace and ID (`Co1|CB`), or we could combine them (as originally proposed) with a period (`Co1.CB`).

The latter (combination with a period) has the advantage, that we know exactly, how many "recipient" frames we have (one), however the period will be a forbidden character. Including return address, it will be `Co1.CB|Co1.CA|Content`(message from CA to CB in the same namespace, the second frame is the return address).

The former (separated by frames) could have any namespace and Component ID, but we will not know, whether the recipient is specified with or without namespace, such that we need empty frames for separation between recipient and sender address, and between sender address and Content: `Co1|CB||Co1|CA||Content`.

More consequences:
- Now the Coordinator does not change the message anymore (the ROUTER does not consume frames, except for the added identity frame), so the Component adds its own address and not the Coordinator?

**Comment by bmoneke** [comment]
Your diagram shows exactly, what I have implemented in my test system 😁  (differently encoded, but same principle)

Thinking more about it:

> I thought that it was a very neat way of doing things, and having zmq do that for us

I agree, I really liked that "deprecated" model with setting the identities, instead of needing to look up the address in a dictionary etc.
The ROUTER will continue to provide that option of user settable identities, so I do not think we will risk a non working protocol (infact, they renamed the option from "IDENTITY" to "ROUTING_ID" in some of the last versions, which would not be necessary, if you drop it).
I'm unsure what path we should take.

**Comment by bilderbuchi** [comment]
> we might want to actually do that on the application level ourselves, with more detailed handshaking in the connecting interaction

I thought so too, it seems to me we should be able to avoid that with some handshaking logic in the beginning.

As One thing we could do

> The latter (combination with a period) has the advantage, that we know exactly, how many "recipient" frames we have (one), however the period will be a forbidden character. Including return address, it will be `Co1.CB|Co1.CA|Content`(message from CA to CB in the same namespace, the second frame is the return address).

This sounds like a good approach. Forbidding a period seems OK for me -- periods as separators are familiar to users from URLs, too.

> so the Component adds its own address and not the Coordinator?

sounds reasonable. Added benefit: constant number of header frames (so payload is always third).

**Comment by bilderbuchi** [comment]
> I agree, I really liked that "deprecated" model with setting the identities, instead of needing to look up the address in a dictionary etc.
> The ROUTER will continue to provide that option of user settable identities, so I do not think we will risk a non working protocol (infact, they renamed the option from "IDENTITY" to "ROUTING_ID" in some of the last versions, which would not be necessary, if you drop it).
> I'm unsure what path we should take.

I'm not sure if what I'll propose will alleviate your indecision, or worsen it.

I agree with you that it would be nice to keep the human-readable IDs also as zmq addresses. I understood from above that if a Component connects with an already used ID, bad things happen (it won't be able to communicate).

Alternatively, we could, as part of the initial contact, let a component ask if its name is available, and if yes, take it. Like this:
```mermaid
sequenceDiagram
    participant dae456
    participant Coordinator
    participant CA
    Note over dae456 : "Random ID - no collision"
    dae456->>Coordinator: `CONNECT'
    Coordinator->>dae456: Welcome!
    dae456->>Coordinator: Hi! Is 'CA' still available? (`NAMEREQUEST CA`)
    Coordinator->>dae456: Sure, I'll reserve it for your for 2 seconds.
    dae456->>Coordinator: `DISCONNECT`
    Coordinator->>dae456: Bye!
    CA->>Coordinator: `CONNECT'
    Coordinator->>CA: Welcome!
    Note over Coordinator: Adds CA to address book, rest of handshake
```

**Comment by bmoneke** [comment]
Yes, we could implement this "name request".
If you do not need a specific name (e. G. For a script), you can just live with your random name.

So we have "name request" as a command of a not connected Component, and "connect" (with the current name, be it random or chosen at will - the Coordinator cannot distinguish).

Oh, I see another problem: If some Component connects, but does not send a message, the Coordinator does not know, that this address is used (you cannot ask for all know addresses). Now someone else asks, whether this name is free. The Coordinator answers "yes", and the Component cannot talk.

For checking the address:
We could try to send to that address a message. If it raises an error (with the appropriate setting), this address is not in use yet.

**Comment by bilderbuchi** [comment]
> If some Component connects, but does not send a message, the Coordinator does not know, that this address is used (you cannot ask for all know addresses).

Thta would/could be against the protocol (if they don't send a CONNECT or request an address, first). Of course still possible by other agents, so maybe we can still guard against it.

**Comment by bmoneke** [comment]
> I'm not sure if what I'll propose will alleviate your indecision, or worsen it.

I had already thought about something similar to your proposal before.

My indecision is, regarding the use of the self chosen address.

In the end, we want to have an address book, therefore we can translate Component ID to socket address easily.
If we had not an address book (because we did not see the need), it would be easier to route with self chosen addresses (the Coordinator would not know its peers).

Assigning your own socket address creates complexity (with that initial request etc.), but we (who have already an address book) do not gain anything than one dictionary lookup.

Therefore, I'm for random addresses.

**Comment by bmoneke** [comment]
Another question: How do we address the Coordinator of another Node, as the Node ID is the ID of that Coordinator?
I propose "Co2.", as the second Coordinator sees, that the message arrived at the right Node. Then it tries to send it to a Component with an empty name.
That way, we can more easily distinguish between Components connected to the Coordinator and the Coordinator itself.

An empty address will indicate the local Coordinator. (alternative: a fixed name like "Coordinator") 

Following flow:
If Full ID contains Namespace different from the own Namespace: send vi Dealer to that namespace's Coordinator.
If no Namespace or Namespace is the own one: Send to connected Component of that name, unless no ID given, then it is for the Coordinator itself.

**Comment by bmoneke** [comment]
Only the single Coordinator knows this "Zmq address", as it is just an identifier to get that single connection. It is nothing more than the dictionary key (in fact it is a hash table as well) for the connection. Nobody else knows this key.

On the other hand, we have the problem to synchronize (and keep synced) these two values (do you remember our discussion regarding channel names 😁?).

**Comment by bklebel** [comment]
> Only the single Coordinator knows this "Zmq address", as it is just an identifier to get that single connection. It is nothing more than the dictionary key (in fact it is a hash table as well) for the connection. Nobody else knows this key.

I agree with @bmoneke that as soon as we keep and address-list ourselves, having to allow Components to choose their identities themselves (with human-readable names), which essentially do not mean anything at all in the whole rest of the network, would be a waste of time and energy. 
> Don't we also gain that we don't have to carry "duplicate" information in our messages (recipient clearname and zmq address can be the same)?

We do not have to carry duplicate information if the Component does not include its name into any message subsequent to a CONNECT. However, then the ROUTER in Co1 needs to put the name from who that now came into something, and that would again make things unnecessarily complicated. Let's do it as @bmoneke suggested above, use periods to delineate namespaces, so a typical message from CA to CB (over one Coordinator only right now) would appear for the ROUTER socket in the Coordinator like this (after having connected earlier): 
`| rnd garbage A | CB | CA | messageID | conversationID | payload |`, so that the ROUTER will do a `send_multipart` with 
`| rnd garbage B | CB | CA | messageID | conversationID | payload |`, where `rnd garbage X` stands for the zmq routing_ID/identity of the corresponding component. 

If we want to go across two Coordinators, we have it like this: 
Co1 ROUTER recv multipart: 
`| rnd garbage A | CB | CA | messageID | conversationID | payload |` -- Co1 does not know CB itself, but looks it up in its "global address list" and finds it in Co2, sending it on via DEALER
Co2 ROUTER recv multipart: 
`| rnd garbage Co1 | CB | Co1.CA | messageID | conversationID | payload |`
Co2 translates CB into `rnd garbage B`, and sends it on as send multipart
`| rnd garbage B | CB | Co1.CA | messageID | conversationID | payload |`

Now CB compiles an answer, and Co2 ROUTER does recv multipart
`| rnd garbage B | Co1.CA | CB | messageID-2 | conversationID | reply |` -- Co2 now already knows Co1, does not need to look it up, sending it on via DEALER
Co1 ROUTER recv multipart: 
`| rnd garbage Co2 | Co1.CA | CB | messageID-2 | conversationID | reply |`


Like this, as mentioned above, the only restriction on the human-chosen ID's will be not to include periods. 
Co1 translates CA into `rnd garbage A`, and does send multipart, scrapping its own namespace from the receiver frame: 
`| rnd garbage A | CA | CB | messageID-2 | conversationID | reply |`
CA can now check that it itself is in the receiver frame (if it wants).

**Comment by bklebel** [comment]
I am now mostly concerned with the first 3 frames here, the part of `| messageID | conversationID | reply |` is part of the discussion in #33 I think, I just did not want to not include something here

**Comment by bmoneke** [comment]
> | rnd garbage A | CB | CA | messageID | conversationID | payload | -- Co1 does not know CB itself, but looks it up in its "global address list" and finds it in Co2, sending it on via DEALER

That should be `| rnd garbage A | Co2.CB | Co1.CA | messageID | conversationID | payload |`, as we said names are unique only in the namespace. Therefore Co1 cannot know to which Coordinator CB belongs, as there could be "Co2.CB" and "Co3.CB".

Additionally, I would always require the sender ID to include the namespace (to be globally unique and thus routable). As the Component receives the namespace during handshake, it can always add the namespace without user intervention.

Maybe we could allow to drop the namespace of the sender, if the recipient is in the same namespace as well.

**Comment by bklebel** [comment]
> That should be `| rnd garbage A | Co2.CB | Co1.CA | messageID | conversationID | payload | `, as we said names are unique only in the namespace. Therefore Co1 cannot know to which Coordinator CB belongs, as there could be "Co2.CB" and "Co3.CB".

> Additionally, I would always require the sender ID to include the namespace (to be globally unique and thus routable). As the Component receives the namespace during handshake, it can always add the namespace without user intervention.

Okay, I agree. 

> Maybe we could allow to drop the namespace of the sender, if the recipient is in the same namespace as well.

I guess it would be simpler not to allow that. If somebody wants to use strictly only one Node with one Control-Coordinator, they can then use (eventually) LMT, and there we can drop all namespaces. I do not think we would gain anything from allowing that, we would just have to implement one more test compared to the situation where we have many Coordinators.

**Comment by bmoneke** [comment]
I prefer a fixed name like Coordinator or, as in the PR and proposed above (https://github.com/pymeasure/leco-protocol/issues/27#issuecomment-1413194690), no name at all.

That way it is easier to address the Coordinator, especially during the handshake, when the Component does not know the Coordinator and namespace yet.

For that special case, we still can allow to not supplying the reciepient information.

**Comment by bklebel** [comment]
> when the Component does not know the Coordinator and namespace yet.

Good point, I did not think of that. 
Yes, but then I prefer a fixed name over nothing, in general. 
If CA connects for the first time, it sends `| Coordinator.Coordinator | Coordinator.CA | `

After connecting, we would have CA sending a message to Co1 which is intended for Co1 as 
`| Coordinator.Coordinator | Co1.CA | `, with explicit namespaces and ID's being fixed - that way, a Component could also address a "remote" Coordinator, for example to ask for their address-book (i.e. CA, which is connected to Co1 but wants to talk to Co2 sends 
`| Co2.Coordinator | Co1.CA |`. 

> For that special case, we still can allow to not supplying the reciepient information.

I think we here I would still supply "Coordinator", and ask for that, but possibly drop the constraint on the sender information, because this is essentially what is not known.

**Comment by bmoneke** [comment]
> Yes, but then I prefer a fixed name over nothing, in general.

Thinking about this topic, I came to the same conclusion.

I would like to avoid "Coordinator" as a namespace, so the very first message would be `|Coordinator|CA|CONNECT|`.
The first frame "Coordinator" is legal, as it is in the same Node. The second frame is illegal, but can be permitted for the CONNECT message.

> i.e. CA, which is connected to Co1 but wants to talk to Co2 sends | Co2.Coordinator | Co1.CA |.

Yes, that would be the consequence.

**Comment by bilderbuchi** [comment]
Having caught up, I agree with using random things for the zmq ids, and keep a hashmap connecting those to the humand-readable names.
I agree with always using the full addresses. (Implementations could always strip a common namespace e.g. in plotting/data storage if they want).

I agree with using a fixed name for the Coordinator. As having one Coordinator per Node (=namespace), we don't have a need for specific Coordinator names. This although in principle, a Coordinator is a Component like the others, so it should have a name it can choose for itself.

**Comment by bilderbuchi** [comment]
I like the idea introduced in the PR that we have a "Node ID", which is our "namespace". I like this and think we should tie the "namespace" concept to the "Node", not the Node's Coordinator. (Of course, the Coordinator will keep track of the namespace and other Node details like transport mode, etc.. Probably, the namespace--- e.g. "beamline"---will be defined by the user when instantiating a Coordinator)

I think it fair that we have exceptions for the address format in case of `SIGN_ON`, so I think we can just define that in that case only, the (unknown) namespace does _not_ have to be given.

**Comment by bilderbuchi** [comment]
> After connecting, we would have CA sending a message to Co1 which is intended for Co1 as
> `| Coordinator.Coordinator | Co1.CA | `

This should be  `| Co1.Coordinator | Co1.CA | ` imo -- at this point, `CA` already knows the namespace it's in, so should address the Coordinator properly.

**Comment by bmoneke** [comment]
> If that complicates our routing logic too much

Tl, dr: no problem. 

We're talking about the ID of the **sender**, which does not matter for the routing of the message. So, no it does not change anything in the routing.

In fact, technically, the sender ID ist only relevant for the response routing, not for the original's message routing itself.
So it is only the protocol definition, which requires a sender ID (and proper working of responses).

**Comment by bklebel** [comment]
> In fact, technically, the sender ID ist only relevant for the response routing, not for the original's message routing itself.
So it is only the protocol definition, which requires a sender ID (and proper working of responses).

I agree. 
As per the discussion in #33 this seems sorted out. 

So, summarizing, the only constraint on a Component ID is now that it cannot include a period ".", right?

**Comment by bmoneke** [comment]
> So, summarizing, the only constraint on a Component ID is now that it cannot include a period ".", right?

Right

**Comment by bmoneke** [comment]
We agreed on the NAMES (not ID anymore), so this can be closed.

**Comment by bmoneke** [comment]
I forgot, one question remains:

What is the Component Name of the Coordinator?

- Coordinator (easy to address, my favourite)
- The namespace?
- Some other fixed name?

**Comment by bklebel** [comment]
I think "Coordinator" would be best, or in caps, "COORDINATOR", to indicate that this really is a constant value

**Comment by bmoneke** [comment]
I'm fine with COORDINATOR.
That is actually the placeholer I used in the document 😁
