### ISSUE TITLE
Component names printable ASCII only?

### ISSUE THREAD

**Issue by bilderbuchi** [pymeasure/leco-protocol#47]
In #38, we decided that

> A Component name must be a series of ASCII characters, without the character "."

_Originally posted by @bilderbuchi in https://github.com/pymeasure/leco-protocol/pull/38#discussion_r1106333828_
            
To avoid shenanigans with escape sequences or whatnot, I would prefer to restrict this to the *printable* ASCII range except `.`,   i.e. 0x20 to 0x7E, excluding 0x2E.

Thoughts?

**Comment by bmoneke** [comment]
I'm fine with it.

I don't see any good reason, why someone could neet a carriage return or new line etc as a Charakter in a name.
